### ISSUE TITLE
Invalid move allowed

### ISSUE THREAD

**Issue by fewdea** [onnixio/2048#2]
This should throw an InvalidMove exception:

    >>> print g
    4   0   0   0
    8   2   0   0
    32  4   0   0
    128 2   16  2
    >>> g.move('d')
    True
    >>> print g
    4   0   0   0
    8   2   0   2
    32  4   0   0
    128 2   16  2

**Comment by onnixio** [comment]
Fixed in cd1daf9

**Comment by onnixio** [comment]
Fixed in 087ae17
