### ISSUE TITLE
Different invalid move allowed

### ISSUE THREAD

**Issue by fewdea** [onnixio/2048#3]
Nonsensical moves trigger the addition of new tile, and don't throw an InvalidMove exception

    >>> print g
    0   0   2   0
    8   0   0   0
    64  8   4   0
    128 2   16  4
    >>> g.move('z')
    True
    >>> print g
    0   0   2   0
    8   0   0   0
    64  8   4   4
    128 2   16  4

**Comment by onnixio** [comment]
Fixed in cd1daf9
