### ISSUE TITLE
Collapse bug

### ISSUE THREAD

**Issue by fewdea** [onnixio/2048#4]
This collapse behavior is not correct. An 'up' move was issued.

    -----------------
    Score: 896
    4   2   0   0
    8   2   2   0
    32  0   0   0
    128 4   0   0
    -----------------
    Score: 908
    4   8   2   2
    8   0   0   0
    32  0   0   0
    128 0   0   0

**Comment by onnixio** [comment]
Fixed in ed8b1cc
