### ISSUE TITLE
Undo doesn't work after invalid move

### ISSUE THREAD

**Issue by fewdea** [onnixio/2048#5]
4 2 4 2
    . . . .
    8 4 2 .
    8 4 2 .
    -----------------
    Score: 40

Press: 'l'

    4 2 4 2
    . . . .
    8 4 2 .
    8 4 2 .
    -----------------
    Score: 40
    Invalid move!

Press 'u'

    4 2 4 2
    . . . .
    8 4 2 .
    8 4 2 .
    -----------------
    Score: 40

Again, press 'u'

    4 2 4 2
    . . . .
    8 4 2 .
    8 4 2 .
    -----------------
    Score: 40
    Can't undo!

**Comment by onnixio** [comment]
Fixed in fb1b3a2
