### ISSUE TITLE
Save key not displaying in help menu

### ISSUE THREAD

**Issue by fewdea** [onnixio/2048#6]
I see there is a save key registered in cli_client.py, but this key is not displaying in the help menu:

    512 .   .   .
    128 2   .   .
    32  4   .   .
    16  8   4   .
    ----------------
    Hi score: 4936
    Score:    4936
    Toggles:
      c : Score
      i : Hi score
      m : Messages
      h : Help text
      q : Quit
      n : New game
      u : Undo

**Comment by onnixio** [comment]
Resolved in f648389
